CREATE TABLE usuarios(
  id INTEGER AUTO_INCREMENT PRIMARY KEY, 
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE, 
  password VARCHAR(50) NOT NULL, 
  phone VARCHAR(50) NOT NULL, 
  address VARCHAR(100) DEFAULT "", 
  grade VARCHAR(10) NOT NULL, 
  role VARCHAR(10) NOT NULL, 
  age VARCHAR(10) NOT NULL,
  description VARCHAR(200) DEFAULT ""
);